### ISSUE TITLE
LAB8

### ISSUE THREAD

**Issue by smsarov** [smsarov/8lab#1]
# Отчет по лабораторной работе 8, 3 вариант 

## Задание: 
Требуется запрограммировать метод решения задачи Коши для ОДУ.
Программа должна работать для произвольной размерности системы уравнений.
Метод Рунге-Кутты 3 порядка
Функция правой части системы и начальное условие подаются на вход программе. Вычисления должны производиться с пошаговым контролем точности по правилу Рунге. Если на текущем шаге точность не достигается, то шаг уменьшается в 2 раза, если достигнутая погрешность меньше заданной в 64 раза, то шаг увеличивается в 2 раза.

# Описание алгоритма 
##псевдокод
*(написал как смог, питон мало отличается от псевдокода конкретно в этом случае)*

```
input t_0
input T
input h_0
input N
input eps

input n
function = []
for i from 0 to n+3:
    function.append(input())
function = join strings in function with newline separator

execute(function)

initial_conditions = split input() into list of integers

kounter = [0]

function step(t, v, h):
    k1 = fs(t, v, kounter)
    k2 = fs(t + h / 2, v + h * k1 / 2, kounter)
    k3 = fs(t + h, v - h * k1 + 2 * h * k2, kounter)
    return v + (h / 6) * (k1 + 4 * k2 + k3)

function try_step(t, v, h):
    v2 = step(t, v, h)
    t2 = t + h
    v2_1 = step(t, v, h / 2)
    t2_1 = t + h / 2
    v2_2 = step(t2_1, v2_1, h / 2)
    R = norm(v2 - v2_2) / 7
    return R, t2, v2_2

function solve():
    t = t_0
    h = h_0
    v = array(initial_conditions)
    print t_0, h_0, 0, 0, *[x for x in v]
    while t < T and kounter[0] < N:
        R, t2, v2 = try_step(t, v, h)
        while R > eps:
            h /= 2
            R, t2, v2 = try_step(t, v, h)
        while R < eps / 64:
            h *= 2
            R, t2, v2 = try_step(t, v, h)
        t = t2
        v = v2
        print t, h, R, kounter[0], *[x for x in v]

solve()
```

## Запуск
> ```python main.py```

##Результат
<img width="762" alt="image" src="https://github.com/smsarov/8lab/assets/47943520/002e77f9-ddcd-442d-a53c-0e83c60c4393">

## Графики

-изменение шага по отрезку для разных значений заданной точности
<img width="591" alt="image" src="https://github.com/smsarov/8lab/assets/47943520/e896496d-0371-4a42-ac68-beac2ca952f6">

-зависимость минимального шага от заданной точности,
<img width="587" alt="image" src="https://github.com/smsarov/8lab/assets/47943520/032d601d-0754-475e-9c31-150ed1ca0cc1">

-зависимость числа шагов от заданной точности
<img width="602" alt="image" src="https://github.com/smsarov/8lab/assets/47943520/1d6b49b6-9842-4fc1-a495-846781beac8e">

-решение для разных значений заданной точности.
<img width="608" alt="image" src="https://github.com/smsarov/8lab/assets/47943520/0340752a-1cdb-421d-848a-918dcf6c5acc"> 

@mackoel

**Comment by mackoel** [comment]
Александр, последний график не совсем понятен, предполагается график каждой компоненты решения от t и все это для разных eps.

**Comment by smsarov** [comment]
Поправил последний график, я правильно понял, что должно выглядеть примерно так?
<img width="892" alt="image" src="https://github.com/smsarov/8lab/assets/47943520/6ff199af-7156-4cba-b780-b1da4f9d0f45">

**Comment by mackoel** [comment]
Да, так годится
